
type User {
  _id: ID
  username: String!
  email: String!
  password: String!
  avatar: String
  joinDate: String
  favorites: [Post]
}

type Post {
  _id: ID
  title: String!
  imageUrl: String!
  description: String!
  createdDate: String
  likes: Int
  createdBy: User!
  comments: [Comment]
}

type Comment {
  _id: ID
  title: String!
  content: String!
} 

type Query {
  posts: [Post]
  post(id: ID!): Post
}

type Mutation {
  addPost(
    title: String!
    imageUrl: String! 
    description: String!
    creatorId: ID!
  ): Post!
}
